### ISSUE TITLE
追加実装　ページネーション

### ISSUE THREAD

**Issue by akari0826** [akari0826/ExpenseApp#17]
### 経費データ一覧画面のページネーション
参考：
[https://github.com/kaminari/kaminari](url)
[https://pikawaka.com/rails/kaminari](url)

1. `gem 'kaminari'`でインストール
`bundle install`も忘れずに

2. コントローラに定義
_app/controllers/admin/expenses_controller.rb_
_app/controllers/expenses_controller.rb_
```
def index
    #N+1問題/検索/ページネーション
    @expenses = Expense.includes(:user).search(expense_search_params).page(params[:page]).per(10)
end
```

3. ビューファイルに追記
_app/views/admin/expenses/index.html.erb_
_app/views/expenses/index.html.erb_
```
<%= paginate @expenses %>
```

4. 表記を日本語化
`$ rails g kaminari:views bootstrap4`

_config/locales/kaminari_ja.yml_
```
ja:
  views:
    pagination:
      first: "&laquo; 最初"
      last: "最後 &raquo;"
      previous: "&lsaquo; 前"
      next: "次 &rsaquo;"
      truncate: "..."
```
