### ISSUE TITLE
Dockerで環境構築

### ISSUE THREAD

**Issue by akari0826** [akari0826/ExpenseApp#34]
参考：https://qiita.com/E6YOteYPzmFGfOD/items/7f9ec4e0f48171e351bd

### 必要なファイルを作成
_Dockerfile_
```
#既存のプロジェクトのrubyのバージョンを指定
FROM ruby:2.6.6 

#パッケージの取得
RUN apt-get update && apt-get install -y --no-install-recommends  \
    nodejs  \
    mariadb-client  \
    build-essential  \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /myproject

COPY Gemfile /myproject/Gemfile
COPY Gemfile.lock /myproject/Gemfile.lock

RUN gem install bundler
RUN bundle install

#既存railsプロジェクトをコンテナ内にコピー
COPY . /myproject
```

- FROM:イメージの取得
- RUN:コマンドの実行。パッケージインストールの為に主に使用。railsで必要になる、nodejs,mysql,build-essentialをインストール。
- `apt-get update && apt-get install -y `：最新版のパッケージを取得しインストール
- WORKDIR:作業ディレクトリの指定。WORKDIR以下の命令を実施する場所を決める。指定したディレクトリがない場合は作成するので「RUN　mkdir」は必要なし。
- COPY：ホストマシンのファイルをコピーする。この場合はホストマシンのGemfile等をコピーする。

_docker-compose.yml_
```
version: '3'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports: 
      - '3306:3306' # ホストからゲストへポートフォワード
    environment:
      MYSQL_DATABASE: expense_app_development
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: test
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes: # データベースで変更されたデータを永続化
      - ./ExpenseApp-master/db/migrate:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true # コンテナ上でbinding.pryするために必要
    stdin_open: true # 同上
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/myproject # ソースコード変更したらDocker側も即反映されるように
```
### 既存のファイルを修正
_config/database.yml_
```
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: test
  password: <%= ENV["DB_PASSWORD"] %>
  # host: localhost # コメントアウト
  # socket: /var/lib/mysql/mysql.sock # コメントアウト

development:
  <<: *default
  database: expense_app_development
  host: db # ここに追加

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: expense_app_test
  host: db # ここに追加
```

_Gemfile_
```
- gem 'mysql2', '>= 0.4.4', '< 0.6.0', group: :development #開発環境でのみ
+ gem 'mysql2', '>= 0.4.4', '< 0.6.0'
​
- gem 'pg'
+ #gem 'pg' #コメントアウトする
```

### イメージの作成とコンテナの立ち上げ
プロジェクトディレクトリにいることを確認し、以下のコマンドを実行
​
```
docker-compose build 
```
​
```
docker-compose up -d
```
​
以下のコマンドを実行し、コンテナが起動していることを確認する。`web`のコンテナのIDをコピーする
​
```
docker ps -a
```
​
以下のコマンドを実行し、マイグレーションを実施する。
`docker-compose exec web`は定型文。`bundle exec~`が通常のrailsのコマンド。`bundle exec~`をつけないと、Gemfile.lockに基づかずにgemのバージョンが決定されるので注意。
​
```
docker-compose exec web bundle exec rails db:migrate
```
​
なお、`docker-compose run web`という記述もあるが、`run`コマンドを使用すると毎回新規のコンテナを作成するので既存のコンテナを作成する場合は`exec`コマンドを使用する。
